#!/usr/bin/env bash
# =============================================================================
# IPAseek Setup Script
# Run this once before using the pipeline.
# Usage: bash setup.sh [--non-interactive]
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/ipaseek.env"

echo "╔══════════════════════════════════════════════════════════╗"
echo "║              IPAseek Setup Configuration                 ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Helper functions ──────────────────────────────────────────────────────────
# prompt_required: loops until user provides a non-blank value (or accepts default)
prompt_required() {
  local var_name="$1"
  local prompt="$2"
  local default="${3:-}"
  local value

  if [[ -n "$default" ]]; then
    read -rp "${prompt} [${default}]: " value
    value="${value:-$default}"
  else
    read -rp "${prompt}: " value
    while [[ -z "$value" ]]; do
      echo "  ✗ This value is required."
      read -rp "${prompt}: " value
    done
  fi
  eval "$var_name='$value'"
}

# prompt_optional: accepts blank input (returns empty string if skipped)
prompt_optional() {
  local var_name="$1"
  local prompt="$2"
  local default="${3:-}"
  local value

  if [[ -n "$default" ]]; then
    read -rp "${prompt} [${default}]: " value
    value="${value:-$default}"
  else
    read -rp "${prompt} (press Enter to skip): " value
  fi
  eval "$var_name='$value'"
}

check_tool() {
  local tool="$1"
  if command -v "$tool" &>/dev/null; then
    echo "  ✓ $tool found: $(command -v $tool)"
  else
    echo "  ✗ $tool NOT found — please install it before running the pipeline"
  fi
}

# ── 1. Project directory ──────────────────────────────────────────────────────
echo "── Step 1: Project directory ─────────────────────────────────"
prompt_required PROJECT_DIR "Absolute path to your IPAseek project directory" "$SCRIPT_DIR"
echo ""

# ── 2. STAR genome index ──────────────────────────────────────────────────────
echo "── Step 2: STAR genome index ─────────────────────────────────"
echo "  The STAR index for hg38 is typically ~30 GB."
echo "  Build it with: sbatch 2_gene_preprocessing/1_rnaseq_pipeline/starindexgenerate.sh"
echo "  (edit that script first to point to your genome FASTA and GTF)"
echo "  Skip this step if you are only running Stage 3 (IPA detection) locally."
echo ""
prompt_optional STAR_INDEX "Path to your STAR genome index directory (hg38)"
if [[ -n "$STAR_INDEX" && ! -d "$STAR_INDEX" ]]; then
  echo "  ⚠ Warning: directory not found — make sure to build the index before running"
elif [[ -z "$STAR_INDEX" ]]; then
  echo "  ℹ Skipped — set IPASEEK_STAR_INDEX later if running Stage 2 (alignment)"
fi
echo ""

# ── 3. Genome annotation object ───────────────────────────────────────────────
echo "── Step 3: Genome annotation object directory ────────────────"
echo "  This directory must contain hg38.cds.rds (used for gene counting)."
echo "  If you have run IPAseek before, this is your annotation_objects/ directory."
echo "  Skip this step if you are only running Stage 3 (IPA detection) locally."
prompt_optional ANNOTATION_DIR "Path to directory containing hg38.cds.rds"
if [[ -n "$ANNOTATION_DIR" && ! -f "${ANNOTATION_DIR}/hg38.cds.rds" ]]; then
  echo "  ⚠ Warning: hg38.cds.rds not found at ${ANNOTATION_DIR}"
elif [[ -z "$ANNOTATION_DIR" ]]; then
  echo "  ℹ Skipped — set IPASEEK_ANNOTATION_DIR later if running Stage 2"
fi
echo ""

# ── 4. SLURM account (optional) ───────────────────────────────────────────────
echo "── Step 4: SLURM account (optional) ─────────────────────────"
echo "  Leave blank if running locally (--mode local) or if your cluster"
echo "  does not require --account."
# Try to auto-detect
AUTO_ACCOUNT=""
if command -v sacctmgr &>/dev/null; then
  AUTO_ACCOUNT=$(sacctmgr show user "$(whoami)" -n format=Account 2>/dev/null | awk '{print $1}' | head -1 || true)
fi
prompt_optional SLURM_ACCOUNT "SLURM account name" "$AUTO_ACCOUNT"
if [[ -z "$SLURM_ACCOUNT" ]]; then
  echo "  ℹ Skipped — set IPASEEK_SLURM_ACCOUNT later if running on an HPC cluster"
fi
echo ""

# ── 5. Conda environment name ─────────────────────────────────────────────────
echo "── Step 5: Conda environment ─────────────────────────────────"
prompt_required CONDA_ENV "Conda environment name for IPAseek" "ipaseek"
echo ""

# ── Check required tools ──────────────────────────────────────────────────────
echo "── Checking required tools ───────────────────────────────────"
check_tool R
check_tool Rscript
check_tool conda
echo ""
echo "  ── HPC-only tools (skip if running locally) ──"
check_tool STAR
check_tool samtools
check_tool nextflow
echo ""

# ── Write config file ─────────────────────────────────────────────────────────
cat > "$CONFIG_FILE" <<EOF
# IPAseek configuration — generated by setup.sh on $(date)
# Source this file before running: source ipaseek.env
export IPASEEK_PROJECT_DIR="${PROJECT_DIR}"
export IPASEEK_STAR_INDEX="${STAR_INDEX}"
export IPASEEK_ANNOTATION_DIR="${ANNOTATION_DIR}"
export IPASEEK_SLURM_ACCOUNT="${SLURM_ACCOUNT}"
export IPASEEK_CONDA_ENV="${CONDA_ENV}"
EOF

echo "╔══════════════════════════════════════════════════════════╗"
echo "║                  Setup Complete!                         ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "Configuration saved to: $CONFIG_FILE"
echo ""
echo "To run the pipeline:"
echo ""
echo "  # Local mode (no SLURM — works on any machine)"
echo "  source ipaseek.env"
echo "  Rscript 3_ipa_run/scripts/0_ipa_detect_run.r \\"
echo "      --project_dir \$IPASEEK_PROJECT_DIR \\"
echo "      --data_table  input_data_tables/data_table_test2_local.txt \\"
echo "      --atlas_name  test2 \\"
echo "      --mode        local"
echo ""
echo "  # SLURM/HPC mode"
echo "  source ipaseek.env"
echo "  nextflow run nextflow/main.nf \\"
echo "      --data_table input_data_tables/data_table_test.txt \\"
echo "      --atlas_name my_experiment \\"
echo "      --outdir results"
echo ""
